# Generated by Django 6.0.1 on 2026-01-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='whatsapp_number',
        ),
    ]
